cache:
  directories:
  - node_modules # cache node_module
language: node_js # set language to node_js
node_js:
  6 # use node version 7
branches:
  only:
  - master # auto build and deploy in only master branch
script: # run after installed
# - npm install # install node module
- npm run build # build project
# install:
  # npm install -g firebase-tools # install firebase-cli
after_success:
- firebase use --token "1/kfCP-kaLEQEvMA8FuetSDGIZTjNdvbyfgoIedU5Lu90" # set firebase token
- firebase use --add "deploy-react-project-example" # set current project
- firebase deploy --non-interactive --token "1/kfCP-kaLEQEvMA8FuetSDGIZTjNdvbyfgoIedU5Lu90" # deploy project
